plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false

# Metrics configurations

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 65

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

# Layout configurations
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Style configurations
Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

# Lint configurations
Lint/DuplicateMethods:
  Enabled: false  # We use method overloading pattern in some cases

# RSpec configurations
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/ReceiveMessages:
  Enabled: false

# Security configurations
Security/MarshalLoad:
  Exclude:
    - 'lib/hati_config/cache.rb'  # Required for caching complex objects
